version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: mds_postgres
    environment:
      POSTGRES_DB: mdsdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: punekar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mds-net
    restart: always
    

  rest-service:
    build: ./rest-service
    container_name: rest_service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mdsdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: punekar
      # OpenTelemetry auto-instrumentation (mount agent jar at /opentelemetry/...)
      JAVA_TOOL_OPTIONS: -javaagent:/opentelemetry/opentelemetry-javaagent.jar
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_RESOURCE_ATTRIBUTES: service.name=rest-service
      OTEL_PROPAGATORS: tracecontext,baggage
      OTEL_TRACES_SAMPLER: always_on
      OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_HEADERS: X-Demo-Id
    volumes:
      - ./opentelemetry-javaagent.jar:/opentelemetry/opentelemetry-javaagent.jar:ro
    ports:
      - "8080:8080"
    networks:
      - mds-net
    restart: always

  grpc-service:
    build: ./grpc-service
    container_name: grpc_service
    depends_on:
      - postgres
      - jaeger
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mdsdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: punekar
      # OpenTelemetry auto-instrumentation (mount agent jar at /opentelemetry/...)
      JAVA_TOOL_OPTIONS: -javaagent:/opentelemetry/opentelemetry-javaagent.jar
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_RESOURCE_ATTRIBUTES: service.name=grpc-service
      OTEL_PROPAGATORS: tracecontext,baggage
      OTEL_TRACES_SAMPLER: always_on
      OTEL_INSTRUMENTATION_GRPC_SERVER_CAPTURE_HEADERS: x-demo-id
    volumes:
      - ./opentelemetry-javaagent.jar:/opentelemetry/opentelemetry-javaagent.jar:ro
    ports:
      - "9090:9090"
    networks:
      - mds-net
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.49
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Jaeger collector (HTTP)
      - "14250:14250" # Jaeger gRPC (optional)
    restart: unless-stopped
    networks:
      - mds-net

volumes:
  postgres_data:

networks:
  mds-net:
    driver: bridge
