spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mdsdb
    username: appuser
    password: punekar
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update