grpc:
  server:
    port: 9090
    enable-reflection: true
spring:
  application:
    name: grpc-service
  datasource:
    url: jdbc:postgresql://postgres:5432/mdsdb
    username: appuser
    password: punekar
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect